from math import log10, sqrt
import cv2
import numpy as np

def PSNR(optical, sar2op): #optical for sen-2 and sar2op for optical img generated by model
	mse = np.mean((optical - sar2op) ** 2)
	if(mse == 0): # MSE is zero means no noise is present in the signal .
				# Therefore PSNR have no importance.
		return 100
	max_pixel = 255.0
	psnr = 20 * log10(max_pixel / sqrt(mse))
	return psnr

def main():
	optical = cv2.imread("original_image.png")
	sar2op = cv2.imread("generated_image.png", 1)
	value = PSNR(optical, sar2op)
	print("PSNR value is {value} dB")
	
if __name__ == "__main__":
	main()
